name: Render

on:
  workflow_dispatch: null
  schedule:
    - cron: '0 6 * * 1'  # Mondays at 6am
  pull_request: null

concurrency: render

jobs:
  readme:
    name: README
    runs-on: "ubuntu-latest"
    permissions:
      contents: write # for git push
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"
      - name: Setup dependencies
        run: python -m pip install -r scripts/requirements.txt
      - name: Rerender README
        run: python scripts/plugin_list.py README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Preview changes
        run: git diff -- README.md
      - name: Commit to repo
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase false
          
          git add README.md
          git commit --allow-empty -m '[ci skip] Rerender README'
          git pull
          git push
